version: 0.2

env:
  parameter-store:
    DOCKERHUB_USER: "/docker/username"
  secrets-manager:
    DOCKERHUB_TOKEN: docker_credentials:token  

phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin 
  build:
    commands:
      - docker build -t my-angular-app:latest .

  post_build:
    commands:
      - docker tag my-angular-app:latest ${DOCKERHUB_USER}/angular-docker-repo-b10:env
      - docker push ${DOCKERHUB_USER}/angular-docker-repo-b10:env
